sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

install:
  - npm install -g codecov
  - npm install

script:
  - docker version
  - docker run --name vault -e 'SKIP_SETCAP=true' -d -p "8200:8200" vault
  - docker ps
  - docker logs vault
  - npm run complete-test

after_success:
  - codecov
