version: '2'
services:
  test:
    build: .
    command: yarn complete-test
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - $PWD/coverage:/app/coverage
    depends_on:
      - vault

  vault:
    image: vault
    volumes:
      - $PWD/examples:/tmp/examples
      - $PWD/logs/:/tmp/logs
    cap_add:
      - IPC_LOCK
    command: server -config /tmp/examples/config.hcl
    ports:
      - "8200:8200"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
